name: flutter_demo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 转语言处理库配置国际化
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^0.1.3 # 图标库
  flutter_screenutil: ^2.3.1 # 适配不同的手机
  intl: ^0.16.1 # 时间格式化工具
  flutter_easyrefresh: ^2.1.5 # 上拉和下拉刷新
  scoped_model: ^1.0.1 # 状态管理库
  rxdart: ^0.24.1 # 状态管理库 不太好用
  provide: ^1.0.2 # 状态管理库 官方推荐的
  provider: ^4.3.2+1 # 状态管理库
  image_picker: ^0.6.7+7 # 图片选择器
  video_player: ^0.10.12+2 # 视频播放器
  path_provider: ^1.6.14 # 获取系统目录
  flutter_swiper: ^1.1.6 # 轮播图库
  fluttertoast: ^7.0.4 # toast 提示库
  http: ^0.12.1 # http发起请求库，在是简单版，一般使用dio
  dio: ^3.0.9 # http发起请求库
  flutter_swipe_action_cell: ^1.0.5+7 # 仿微信的滑动一行删除功能
  date_format: ^1.0.8 #格式化日期和时间库
  flutter_cupertino_date_picker: ^1.0.26+2 # 日期和时间选择库
  marquee: ^1.6.0 # 跑马灯公告
  flutter_jpush: ^0.0.4 # 极光推送

  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  # 本地图片
  assets:
    - assets/images/
  # 自定义字体
  fonts:
    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf
          style: italic # 表示斜体
    - family: LiuJianMaoCao
      fonts:
        - asset: assets/fonts/LiuJianMaoCao-Regular.ttf
          weight: 700 # 表示粗体
    - family: MaShanZheng
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf
    # 下面是自定义阿里图标
    - family: Iconfont
      fonts:
        - asset: assets/icons/iconfont.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
