name: flutter_demo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 转语言处理库配置国际化
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^0.1.3 # 图标库
  flutter_screenutil: ^2.3.1 # 适配不同的手机
  intl: ^0.16.1 # 时间格式化工具
  flutter_easyrefresh: ^2.1.5 # 上拉和下拉刷新
  scoped_model: ^1.0.1 # 状态管理库
  rxdart: ^0.24.1 # 状态管理库 不太好用
  provide: ^1.0.2 # 状态管理库 官方推荐的
  provider: ^4.3.2+1 # 状态管理库
  camera: ^0.5.8+5 # 摄像机
  image_picker: ^0.6.7+7 # 图片选择器
  video_player: ^0.10.12+2 # 视频播放器
  path_provider: ^1.6.14 # 获取系统目录
  flutter_swiper: ^1.1.6 # 轮播图库
  fluttertoast: ^7.0.4 # toast 提示库
  http: ^0.12.1 # http发起请求库，在是简单版，一般使用dio
  dio: ^3.0.9 # http发起请求库
  flutter_swipe_action_cell: ^1.0.5+7 # 仿微信的滑动一行删除功能
  date_format: ^1.0.8 #格式化日期和时间库
  flutter_cupertino_date_picker: ^1.0.26+2 # 日期和时间选择库
  marquee: ^1.6.0 # 跑马灯公告
  flutter_jpush: ^0.0.4 # 极光推送
  shared_preferences: ^0.5.10 # 数据存储
  after_layout: ^1.0.7+2 # 显示第一帧之后提供执行方法 afterFirstLayout
  sticky_headers: "^0.1.8" # 滚动连贴头部效果
  flutter_staggered_animations: ^0.1.2 # 列表动画 https://xbzweb.com/
  like_button: ^0.1.9 # 点赞按钮动画 https://xbzweb.com/
  photo_view: ^0.7.0 # 可定制的图片预览查看器 https://xbzweb.com/
  flutter_slidable: ^0.5.4 #可滑动列表按钮选项，内置定向滑动删除动作 https://xbzweb.com/
  bot_toast: ^3.0.4  # 提示弹出框 真正意义上的Toast https://xbzweb.com/2019/10/31/flutter%E5%A5%BD%E7%94%A8%E7%9A%84%E8%BD%AE%E5%AD%90%E6%8E%A8%E8%8D%90%E5%85%AD-%E8%B6%85%E5%A5%BD%E7%94%A8%E7%9A%84%E5%85%A8%E5%B1%80toast/#%E8%BD%AE%E5%AD%90
  percent_indicator: ^2.1.6 # 圆形和线形的进度条 https://xbzweb.com/2019/11/04/flutter%E5%A5%BD%E7%94%A8%E7%9A%84%E8%BD%AE%E5%AD%90%E6%8E%A8%E8%8D%90%E4%B8%83-flutter%E5%9C%86%E5%BD%A2%E6%88%96%E7%BA%BF%E5%9E%8B%E8%BF%9B%E5%BA%A6%E6%9D%A1/#%E5%89%8D%E8%A8%80
  curved_navigation_bar: ^0.3.4 # 超酷动画的底部tab栏 https://xbzweb.com/2019/11/04/flutter%E5%A5%BD%E7%94%A8%E7%9A%84%E8%BD%AE%E5%AD%90%E6%8E%A8%E8%8D%90%E5%85%AB-flutter%E4%B8%80%E4%B8%AA%E8%B6%85%E9%85%B7%E5%8A%A8%E7%94%BB%E7%9A%84%E5%BA%95%E9%83%A8tab%E6%A0%8F/#%E8%BD%AE%E5%AD%90
  sliding_up_panel: ^1.0.1  # 可定制的上下滑出抽屉  https://xbzweb.com
  drag_list: ^1.0.8 # 拖动排序 https://xbzweb.com
  animated_text_kit: ^2.2.0 # 文字动效组件 https://xbzweb.com
  flutter_speed_dial: ^1.2.5 # 可展开选项的浮动按钮 https://xbzweb.com
  flutter_custom_clippers: ^1.1.2 # flutter将widget裁剪成各种自定义形状. https://xbzweb.com
  flutter_rating_bar: ^3.0.1+1 # 可自定义的评分组件
  flip_card: ^0.4.4 # 可翻转的卡片组件
  liquid_swipe: ^1.5.0 # 液体效果的页面切换组件
  liquid_progress_indicator: ^0.3.2 # 水波效果的进度器
  passcode_screen: ^1.2.0 # 仿iPhone锁屏界面
  scratcher: ^1.4.0 # 制作刮刮卡效果
  flutter_spinkit: ^4.1.2 # 一个很棒的等待动画库——Spinkit
  url_launcher: ^5.5.3 # 使用url_launcher唤醒功能 :打开网页，打电话，发短信等功能
  multi_image_picker: ^4.7.13 # 从本地相册选取多张图片 https://sh1d0w.github.io/multi_image_picker/#/gettingstarted
  intro_slider: ^2.3.3 # App启动时候应用介绍页——slider
  intro_views_flutter: ^2.8.1 # 一个很棒的开场介绍动画的库
  tobias: ^1.7.1+1 # 支付宝支付 
  line_icons: ^0.2.0 # 图标包
  # pinch_zoom_image: ^0.2.5 # 手指对图片放大缩小
  cached_network_image: ^2.3.2+1 # 图片缓存
  wave: ^0.1.0 # 绘制水波纹特效 https://github.com/i-protoss/wave
  bottomreveal: ^1.0.0 # 底部导航栏
  animated_floatactionbuttons: ^0.1.0 # 浮动按钮
  flare_flutter: ^1.8.3 # 使用Flare做动画
  flutter_staggered_grid_view: ^0.3.0 # 实现分页瀑布流效果
  crop: ^0.1.2 # 头像上传功能，实现照片选择及裁剪
  share: ^0.6.4+3 # 分享功能
  animator: ^2.0.1 # 制作动画
  font_awesome_flutter: ^8.8.1 # 

# 开发包
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # 本地图片
  assets:
    - assets/images/
    - assets/videos/
    - assets/smwallet/
    - assets/hotel/
    - assets/flare/
    - assets/nicasiaassets/
    
  # 自定义字体
  fonts:
    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf
          style: italic # 表示斜体
    - family: LiuJianMaoCao
      fonts:
        - asset: assets/fonts/LiuJianMaoCao-Regular.ttf
          weight: 700 # 表示粗体
    - family: MaShanZheng
      fonts:
        - asset: assets/fonts/MaShanZheng-Regular.ttf
    - family:  TikTokIcons
      fonts:
         - asset: assets/fonts/TikTokIcons.ttf
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
        
    # 下面是自定义阿里图标
    - family: Iconfont
      fonts:
        - asset: assets/icons/iconfont.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
